//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocolizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocolizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Owen.App_GlobalResources.LocolizationResource", typeof(LocolizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О компании.
        /// </summary>
        public static string aboutCompany {
            get {
                return ResourceManager.GetString("aboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string aboutCompany_Contacts {
            get {
                return ResourceManager.GetString("aboutCompany_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости и статьи.
        /// </summary>
        public static string aboutCompany_news {
            get {
                return ResourceManager.GetString("aboutCompany_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции и предложения.
        /// </summary>
        public static string aboutCompany_shareAction {
            get {
                return ResourceManager.GetString("aboutCompany_shareAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройства связи.
        /// </summary>
        public static string catalog_MainCategory_Communication {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приборы контроля и управления.
        /// </summary>
        public static string catalog_MainCategory_ManageControl {
            get {
                return ResourceManager.GetString("catalog_MainCategory_ManageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электротехническое оборудование Meyertec.
        /// </summary>
        public static string catalog_MainCategory_Meyertec {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Meyertec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модули ввода/вывода.
        /// </summary>
        public static string catalog_MainCategory_MV {
            get {
                return ResourceManager.GetString("catalog_MainCategory_MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив продукции.
        /// </summary>
        public static string catalog_MainCategory_OldProd {
            get {
                return ResourceManager.GetString("catalog_MainCategory_OldProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панели оператора.
        /// </summary>
        public static string catalog_MainCategory_OperatorPanel {
            get {
                return ResourceManager.GetString("catalog_MainCategory_OperatorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программируемые логические контроллеры.
        /// </summary>
        public static string catalog_MainCategory_PLC {
            get {
                return ResourceManager.GetString("catalog_MainCategory_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блоки питания и устройства коммутации.
        /// </summary>
        public static string catalog_MainCategory_Power {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приводная техника.
        /// </summary>
        public static string catalog_MainCategory_Privod {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Privod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерители-регуляторы.
        /// </summary>
        public static string catalog_MainCategory_Reguliators {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Reguliators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датчики.
        /// </summary>
        public static string catalog_MainCategory_Sensors {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программное обеспечение.
        /// </summary>
        public static string catalog_MainCategory_Softweare {
            get {
                return ResourceManager.GetString("catalog_MainCategory_Softweare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сенсорные панельные контроллеры.
        /// </summary>
        public static string catalog_MainCategory_SPC {
            get {
                return ResourceManager.GetString("catalog_MainCategory_SPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программируемые реле.
        /// </summary>
        public static string catalog_MainCategory_switches {
            get {
                return ResourceManager.GetString("catalog_MainCategory_switches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rus culture selected.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWENfast.kh@gmail.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWEN Fast.
        /// </summary>
        public static string LOGO {
            get {
                return ResourceManager.GetString("LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнёры.
        /// </summary>
        public static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата и доставка.
        /// </summary>
        public static string paymentDeliver {
            get {
                return ResourceManager.GetString("paymentDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +38 066 820 54 09.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог проектов.
        /// </summary>
        public static string projectCatalog {
            get {
                return ResourceManager.GetString("projectCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация.
        /// </summary>
        public static string support_documentation {
            get {
                return ResourceManager.GetString("support_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проектировщику в помощь.
        /// </summary>
        public static string support_projHelper {
            get {
                return ResourceManager.GetString("support_projHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертификаты и разрешения.
        /// </summary>
        public static string support_serteficate {
            get {
                return ResourceManager.GetString("support_serteficate", resourceCulture);
            }
        }
    }
}
